tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "shyiko/kubesec"
tap "superbrothers/zsh-kubectl-prompt", "git://github.com/superbrothers/zsh-kubectl-prompt.git"

brew "go"
brew "dep"
brew "git"
brew "jq"
brew "kubectx"
brew "kubernetes-helm"
brew "nkf"
brew "python"
brew "mackup"
brew "nodebrew"
brew "peco"
brew "stern"
brew "skaffold"
brew "terraform"
brew "tree"
brew "wget"
brew "yarn"
brew "zsh"
brew "shyiko/kubesec/kubesec"
brew "superbrothers/zsh-kubectl-prompt/zsh-kubectl-prompt"

cask "minikube"
cask "virtualbox"
